"""
ORM models. TimescaleDB hypertables are created via raw SQL in the migration
(see alembic/versions/) — the ORM definitions are standard SQLAlchemy.
"""
import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import (
    Boolean, DateTime, Float, ForeignKey, Integer,
    String, Text, UniqueConstraint, func,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.session import Base


# ─── Article ──────────────────────────────────────────────────────────────────

class Article(Base):
    """Raw ingested article from any source."""
    __tablename__ = "articles"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    source: Mapped[str] = mapped_column(String(64))          # "reuters_rss", "gdelt", "newsapi"
    source_tier: Mapped[int] = mapped_column(Integer, default=2)  # 1=top, 2=standard, 3=low
    url: Mapped[str] = mapped_column(Text, unique=True)
    title: Mapped[str] = mapped_column(Text)
    body: Mapped[Optional[str]] = mapped_column(Text)
    published_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    fetched_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    language: Mapped[str] = mapped_column(String(8), default="en")
    is_processed: Mapped[bool] = mapped_column(Boolean, default=False)

    # Relationships
    analysis: Mapped[Optional["ArticleAnalysis"]] = relationship(back_populates="article", uselist=False)


# ─── ArticleAnalysis ──────────────────────────────────────────────────────────

class ArticleAnalysis(Base):
    """NLP outputs for a single article."""
    __tablename__ = "article_analyses"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    article_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("articles.id"), unique=True)
    analysed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    # Event classification
    event_type: Mapped[Optional[str]] = mapped_column(String(64))   # "armed_conflict", "sanctions", "election", ...
    event_confidence: Mapped[Optional[float]] = mapped_column(Float)

    # Sentiment
    sentiment_label: Mapped[Optional[str]] = mapped_column(String(16))  # "positive", "negative", "neutral"
    sentiment_score: Mapped[Optional[float]] = mapped_column(Float)     # -1.0 to 1.0
    geopolitical_stress: Mapped[Optional[float]] = mapped_column(Float) # 0.0 to 1.0

    # NER — extracted geo entities
    countries: Mapped[Optional[list]] = mapped_column(ARRAY(String))
    actors: Mapped[Optional[list]] = mapped_column(ARRAY(String))
    locations: Mapped[Optional[dict]] = mapped_column(JSONB)  # {country: [lat, lon]}

    # Clustering
    cluster_id: Mapped[Optional[int]] = mapped_column(Integer)          # -1 = noise
    cluster_label: Mapped[Optional[str]] = mapped_column(Text)          # human-readable cluster theme
    embedding_model: Mapped[Optional[str]] = mapped_column(String(64))

    # Relationships
    article: Mapped["Article"] = relationship(back_populates="analysis")


# ─── RegionSignal ─────────────────────────────────────────────────────────────

class RegionSignal(Base):
    """
    Per-region tension index snapshot — one row per (region, timestamp).
    This table is a TimescaleDB hypertable partitioned on `timestamp`.
    """
    __tablename__ = "region_signals"
    __table_args__ = (
        UniqueConstraint("region_code", "timestamp"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    region_code: Mapped[str] = mapped_column(String(8))   # ISO-3166 alpha-3 country code
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True))

    # Core tension index (0–100)
    tension_index: Mapped[float] = mapped_column(Float)
    tension_delta_24h: Mapped[Optional[float]] = mapped_column(Float)  # change from 24h ago

    # Component scores feeding into the index
    conflict_score: Mapped[Optional[float]] = mapped_column(Float)
    sanctions_score: Mapped[Optional[float]] = mapped_column(Float)
    political_instability_score: Mapped[Optional[float]] = mapped_column(Float)
    economic_stress_score: Mapped[Optional[float]] = mapped_column(Float)

    # Article volume (proxy for importance)
    article_count: Mapped[int] = mapped_column(Integer, default=0)


# ─── MarketSignal ─────────────────────────────────────────────────────────────

class MarketSignal(Base):
    """
    Market predictions generated by the LightGBM model.
    TimescaleDB hypertable on `timestamp`.
    """
    __tablename__ = "market_signals"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    horizon_hours: Mapped[int] = mapped_column(Integer)  # 24, 48, 72

    # Predictions
    vix_direction: Mapped[Optional[str]] = mapped_column(String(8))    # "up" | "down" | "neutral"
    vix_confidence: Mapped[Optional[float]] = mapped_column(Float)
    gold_bias: Mapped[Optional[str]] = mapped_column(String(8))        # "bullish" | "bearish" | "neutral"
    gold_confidence: Mapped[Optional[float]] = mapped_column(Float)
    oil_bias: Mapped[Optional[str]] = mapped_column(String(8))
    oil_confidence: Mapped[Optional[float]] = mapped_column(Float)
    macro_risk_quartile: Mapped[Optional[int]] = mapped_column(Integer) # 1–4

    # Feature snapshot used (for explainability)
    feature_snapshot: Mapped[Optional[dict]] = mapped_column(JSONB)


# ─── NarrativeCluster ─────────────────────────────────────────────────────────

class NarrativeCluster(Base):
    """
    A macro narrative cluster — detected by HDBSCAN across article embeddings.
    Updated on each clustering run.
    """
    __tablename__ = "narrative_clusters"
    __table_args__ = (
        UniqueConstraint("cluster_id", name="uq_narrative_clusters_cluster_id"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    cluster_id: Mapped[int] = mapped_column(Integer)           # HDBSCAN cluster id
    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    last_seen_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    label: Mapped[str] = mapped_column(Text)                   # LLM-generated summary label
    keywords: Mapped[Optional[list]] = mapped_column(ARRAY(String))
    article_count: Mapped[int] = mapped_column(Integer, default=0)
    avg_stress: Mapped[Optional[float]] = mapped_column(Float)  # avg geopolitical stress in cluster
    countries: Mapped[Optional[list]] = mapped_column(ARRAY(String))

    # Drift tracking
    stress_7d_ago: Mapped[Optional[float]] = mapped_column(Float)
    stress_delta_7d: Mapped[Optional[float]] = mapped_column(Float)
    is_emerging: Mapped[bool] = mapped_column(Boolean, default=False)


# ─── Alert ────────────────────────────────────────────────────────────────────

class Alert(Base):
    """Triggered alert when a tension threshold is crossed."""
    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    alert_type: Mapped[str] = mapped_column(String(32))  # "tension_spike", "narrative_emerging", "market_signal"
    region_code: Mapped[Optional[str]] = mapped_column(String(8))
    severity: Mapped[str] = mapped_column(String(8))     # "low", "medium", "high", "critical"
    title: Mapped[str] = mapped_column(Text)
    body: Mapped[str] = mapped_column(Text)
    is_sent: Mapped[bool] = mapped_column(Boolean, default=False)
    metadata: Mapped[Optional[dict]] = mapped_column(JSONB)
